spring.application.name=mi_agenda_web
server.port=8081

# Configuracion de la base de datos H2
spring.datasource.url=jdbc:h2:file:./data/agenda-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostrar el SQL en consola
spring.jpa.show-sql=true

# Crear/actualizar las tablas automaticamente
spring.jpa.hibernate.ddl-auto=update